### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [nittka/Xarchive#30]
Hello Xarchive team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the Xarchive project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>
```

We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by nittka** [comment]
Here are the proposed entries for my Xtext projects  - as Xarchive is not the only one.
```
<tr>
	<td><a href="https://github.com/nittka/Xarchive">Xarchive</a></td>
	<td>Lightweight document management.</td>
	<td>EPL</td>
	<td>Language</td>
	<td>Alexander Nittka</td>
</tr>
<tr>
	<td><a href="https://github.com/nittka/Jtag">Jtag</a></td>
	<td>Lightweight image tagging.</td>
	<td>EPL</td>
	<td>Language</td>
	<td>Alexander Nittka</td>
</tr>
<tr>
	<td><a href="https://github.com/nittka/terminology">Terminology</a></td>
	<td>Lightweight terminology management. If spreadsheet is not enough and term bases are overkill, consider this plugin with advanced search functionality and hook for custom exporters.</td>
	<td>EPL</td>
	<td>Language</td>
	<td>Alexander Nittka</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you very much Alexander, we will list all your projects on the Xtext community website.

**Comment by miklossy** [comment]
The `Xarchive`, `Jtag` and the `Terminology` projects have been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).

**Comment by nittka** [comment]
Thanks. When I saw the projects there, I closed the ticket.
